version: "3.3"

#########
## Traefik proxy docker-compose file
##
## Nice for stage servers.
##
## https://github.com/traefik/traefik
##
services:
  traefik:
    image: traefik:v2.8
    container_name: "traefik"
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"      

    volumes:
      - ./letsencrypt:/letsencrypt
      - './data/traefik.yaml:/etc/traefik/traefik.yaml'
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - main

networks:
  main:
    external: true